-- Streamlined ecommerce sample data for text-to-SQL and pgvector demonstrations

-- Users (15 users with aggregated order data)
INSERT INTO users (email, username, first_name, last_name, phone_number, date_of_birth, gender, city, state_province, country_code, total_orders, total_spent) VALUES 
('john.doe@email.com', 'johndoe', 'John', 'Doe', '+1-555-0101', '1985-03-15', 'male', 'New York', 'NY', 'US', 3, 2149.97),
('jane.smith@email.com', 'janesmith', 'Jane', 'Smith', '+1-555-0102', '1990-07-22', 'female', 'Los Angeles', 'CA', 'US', 2, 1449.98),
('mike.johnson@email.com', 'mikej', 'Mike', 'Johnson', '+1-555-0103', '1988-11-30', 'male', 'Chicago', 'IL', 'US', 1, 149.99),
('sarah.williams@email.com', 'sarahw', 'Sarah', 'Williams', '+1-555-0104', '1992-04-18', 'female', 'Houston', 'TX', 'US', 4, 1799.96),
('david.brown@email.com', 'davidb', 'David', 'Brown', '+1-555-0105', '1987-09-05', 'male', 'Phoenix', 'AZ', 'US', 2, 899.98),
('emily.davis@email.com', 'emilyd', 'Emily', 'Davis', '+1-555-0106', '1993-12-10', 'female', 'Philadelphia', 'PA', 'US', 1, 49.99),
('robert.miller@email.com', 'robertm', 'Robert', 'Miller', '+1-555-0107', '1986-06-25', 'male', 'San Antonio', 'TX', 'US', 2, 3299.98),
('lisa.wilson@email.com', 'lisaw', 'Lisa', 'Wilson', '+1-555-0108', '1991-02-14', 'female', 'San Diego', 'CA', 'US', 3, 1249.97),
('james.moore@email.com', 'jamesm', 'James', 'Moore', '+1-555-0109', '1989-08-30', 'male', 'Dallas', 'TX', 'US', 1, 799.99),
('maria.garcia@email.com', 'mariag', 'Maria', 'Garcia', '+1-555-0110', '1994-05-20', 'female', 'San Jose', 'CA', 'US', 2, 549.98),
('kevin.lee@email.com', 'kevinl', 'Kevin', 'Lee', '+1-555-0111', '1988-10-15', 'male', 'Austin', 'TX', 'US', 1, 199.99),
('nancy.clark@email.com', 'nancyc', 'Nancy', 'Clark', '+1-555-0112', '1990-03-28', 'female', 'Jacksonville', 'FL', 'US', 2, 1149.98),
('brian.hall@email.com', 'brianh', 'Brian', 'Hall', '+1-555-0113', '1987-11-08', 'male', 'Fort Worth', 'TX', 'US', 1, 89.99),
('amanda.white@email.com', 'amandaw', 'Amanda', 'White', '+1-555-0114', '1992-07-12', 'female', 'Columbus', 'OH', 'US', 3, 1799.97),
('steven.martin@email.com', 'stevenm', 'Steven', 'Martin', '+1-555-0115', '1985-09-18', 'male', 'Charlotte', 'NC', 'US', 2, 449.98);

-- Categories (Hierarchical structure: Electronics > Sub-categories)
INSERT INTO categories (name, slug, description, parent_category_id, product_count) VALUES 
('Electronics', 'electronics', 'Electronic devices and accessories', NULL, 8),
('Computers & Tablets', 'computers-tablets', 'Desktop computers, laptops, and tablets', 1, 2),
('Audio & Video', 'audio-video', 'Headphones, speakers, and camera equipment', 1, 4),
('Smart Devices', 'smart-devices', 'Smartphones, smartwatches, and wearables', 1, 2),
('Home & Kitchen', 'home-kitchen', 'Home appliances and kitchen items', NULL, 2),
('Books', 'books', 'Physical and digital books', NULL, 1),
('Sports & Outdoors', 'sports-outdoors', 'Sporting goods and outdoor equipment', NULL, 2),
('Games & Toys', 'games-toys', 'Board games and entertainment', NULL, 1);

-- Products (16 products with rich data for analysis)
INSERT INTO products (sku, name, slug, description, short_description, category_id, brand, price, cost, stock_quantity, weight_kg, rating_average, rating_count, total_sales, revenue_generated) VALUES 
('LAPTOP-001', 'UltraBook Pro 15', 'ultrabook-pro-15', 'The UltraBook Pro 15 is a powerhouse designed for professionals who demand the best. Featuring a stunning 15.6-inch 4K OLED display with 100% DCI-P3 color gamut, this laptop delivers breathtaking visuals for creative work and entertainment. Under the hood, the latest 12th Gen Intel Core i7 processor paired with 32GB of lightning-fast DDR5 RAM ensures smooth multitasking and blazing performance. The dedicated NVIDIA RTX 3070 graphics card handles intensive tasks like video editing, 3D rendering, and gaming with ease. With a massive 1TB NVMe SSD, you will have plenty of space for all your files while enjoying near-instantaneous boot times and application launches.', 'High-performance laptop with 4K display and dedicated graphics', 2, 'TechBrand', 1299.99, 899.99, 25, 1.8, 4.5, 3, 15, 19499.85),
('PHONE-001', 'SmartPhone X Pro', 'smartphone-x-pro', 'Experience the future of mobile technology with the SmartPhone X Pro. This flagship device redefines what a smartphone can be, featuring a gorgeous 6.7-inch Super AMOLED display with 120Hz refresh rate for buttery-smooth scrolling and responsive gaming. The revolutionary camera system includes a 108MP main sensor with optical image stabilization, a 12MP ultra-wide lens, and a 10MP telephoto lens with 3x optical zoom, allowing you to capture professional-quality photos and 8K videos. Powered by the latest Snapdragon processor and 12GB of RAM, every app launches instantly and multitasking is effortless.', 'Latest flagship smartphone with advanced camera system', 4, 'PhoneCorp', 999.99, 649.99, 50, 0.195, 4.0, 3, 22, 21999.78),
('BLENDER-001', 'PowerBlend 3000', 'powerblend-3000', 'Transform your kitchen experience with the PowerBlend 3000, the ultimate blending solution for health-conscious individuals and culinary enthusiasts. This professional-grade blender features a powerful 1500W motor that can pulverize even the toughest ingredients, from frozen fruits to nuts and ice. The patented 6-blade system creates a vortex that ensures perfect blending every time, whether you are making smoothies, soups, nut butters, or frozen desserts. The large 2-liter BPA-free Tritan container is virtually unbreakable and dishwasher safe.', 'High-performance blender with multiple preset programs', 5, 'KitchenMaster', 149.99, 79.99, 35, 4.2, 4.7, 3, 45, 6749.55),
('BOOK-001', 'The Art of Coding', 'art-of-coding', 'Dive deep into the world of programming with "The Art of Coding," a comprehensive guide that takes you from beginner to advanced developer. This 800-page masterpiece covers everything from basic programming concepts to advanced algorithms and design patterns. Written by industry veterans with over 20 years of experience, this book uses a hands-on approach with real-world examples and projects. Topics covered include: fundamental programming concepts, data structures and algorithms, object-oriented programming, functional programming paradigms, web development with modern frameworks, mobile app development, database design and optimization, cloud computing and microservices, machine learning basics, and software engineering best practices.', 'Comprehensive programming guide for all skill levels', 6, 'TechBooks Publishing', 49.99, 19.99, 100, 1.2, 4.5, 3, 85, 4249.15),
('TABLET-001', 'TabMax Pro 12', 'tabmax-pro-12', 'The TabMax Pro 12 redefines what a tablet can do, bridging the gap between tablet convenience and laptop productivity. Featuring a stunning 12.9-inch Liquid Retina XDR display with ProMotion technology, every image comes to life with incredible detail and smooth motion. The powerful M2 chip delivers desktop-class performance, handling everything from 4K video editing to complex 3D modeling. With 8GB of RAM and 256GB of storage, multitasking is effortless. Compatible with the Smart Keyboard and Precision Stylus for a complete productivity setup.', 'Professional tablet with laptop-class performance', 2, 'TabTech', 899.99, 599.99, 30, 0.682, 4.2, 1, 18, 16199.82),
('HEADPHONES-001', 'SoundWave Pro', 'soundwave-pro', 'Immerse yourself in pure audio bliss with the SoundWave Pro wireless headphones. Featuring industry-leading active noise cancellation, these headphones create a personal oasis of sound wherever you go. The custom 40mm drivers deliver rich, balanced audio across all frequencies, from deep bass to crystal-clear highs. With 30 hours of battery life and quick charge capability, your music never stops. Includes a premium carrying case and audio cable for wired listening.', 'Premium wireless headphones with active noise cancellation', 3, 'AudioTech', 349.99, 199.99, 60, 0.285, 4.4, 2, 35, 12249.65),
('CAMERA-001', 'ProShot X1', 'proshot-x1', 'Capture life in stunning detail with the ProShot X1 mirrorless camera. The 45MP full-frame sensor delivers exceptional image quality with incredible dynamic range and low-light performance. The advanced autofocus system with 759 phase-detection points ensures sharp focus even on fast-moving subjects. 8K video recording at 30fps and 4K at 120fps opens up creative possibilities for videographers. The weather-sealed magnesium alloy body is built to withstand professional use.', 'Professional mirrorless camera with 45MP sensor', 3, 'PhotoPro', 2499.99, 1899.99, 10, 0.850, 4.8, 1, 8, 19999.92),
('SPEAKER-001', 'SoundBlast 360', 'soundblast-360', 'Experience room-filling 360-degree sound with the SoundBlast 360 wireless speaker. The innovative acoustic design with dual passive radiators delivers deep bass and crystal-clear highs that fill any space. With 20 hours of battery life and IPX7 waterproofing, it is perfect for pool parties, beach trips, or camping adventures. PartyBoost technology lets you connect multiple speakers for an even bigger sound.', 'Portable wireless speaker with 360-degree sound', 3, 'AudioBlast', 149.99, 89.99, 90, 0.960, 4.3, 2, 65, 9749.35),
('WATCH-001', 'FitTrack Ultra', 'fittrack-ultra', 'The FitTrack Ultra is more than a smartwatch - it is your personal health and fitness companion. Featuring advanced health monitoring including ECG, blood oxygen, and continuous heart rate tracking, it provides comprehensive insights into your wellbeing. With built-in GPS and support for 100+ workout modes, it accurately tracks your activities from running to swimming to yoga. Smart features include notifications, contactless payments, music storage, and voice assistant integration.', 'Advanced fitness smartwatch with health monitoring', 4, 'FitTech', 449.99, 249.99, 75, 0.065, 4.1, 1, 28, 12599.72),
('COFFEE-001', 'BrewMaster Pro', 'brewmaster-pro', 'Wake up to barista-quality coffee every morning with the BrewMaster Pro. This fully automatic espresso machine features a built-in conical burr grinder with 15 grind settings, ensuring the perfect extraction every time. The dual boiler system allows simultaneous brewing and steaming, while the PID temperature control maintains optimal brewing temperature. Create your favorite drinks with one touch - from espresso to cappuccino to flat white.', 'Professional espresso machine with built-in grinder', 5, 'CoffeeTech', 1299.00, 899.00, 15, 12.5, 4.6, 1, 12, 15588.00),
('TENT-001', 'Explorer 4-Season Tent', 'explorer-4-season-tent', 'Built for extreme conditions, the Explorer 4-Season Tent is your reliable shelter in the harshest environments. The geodesic dome design with aerospace-grade aluminum poles provides exceptional stability in high winds and heavy snow loads. The double-wall construction with full-coverage fly ensures complete weather protection while minimizing condensation. Accommodates 2-3 people comfortably with room for gear.', 'Professional-grade tent for extreme weather conditions', 7, 'CampPro', 499.99, 299.99, 15, 3.8, 4.3, 1, 8, 3999.92),
('BACKPACK-001', 'Adventure Pro 65L', 'adventure-pro-65l', 'The Adventure Pro 65L is designed for serious backpackers who demand durability and comfort on multi-day adventures. Features a lightweight aluminum frame, multiple compartments for organized packing, and an integrated rain cover. The ventilated back panel and padded shoulder straps ensure comfort even with heavy loads. Side compression straps and external attachment points accommodate extra gear.', 'Heavy-duty backpack for extended hiking trips', 7, 'TrailGear', 199.99, 119.99, 25, 2.1, 4.5, 1, 12, 2399.88),
('BOARDGAME-001', 'Quest for the Crystal Kingdom', 'quest-crystal-kingdom', 'Embark on an epic adventure with Quest for the Crystal Kingdom, a strategic board game for 2-6 players. This beautifully illustrated game combines resource management, tactical combat, and cooperative storytelling. Each player chooses a unique hero with special abilities and embarks on quests to save the kingdom from darkness. Includes over 200 detailed miniatures, 500+ cards, custom dice, and a comprehensive rulebook.', 'Epic adventure board game with miniatures and campaign mode', 8, 'GameCraft', 89.99, 49.99, 45, 2.5, 4.4, 1, 25, 2249.75);

-- Orders (Sample orders with various statuses and amounts)
INSERT INTO orders (order_number, user_id, order_status, payment_status, shipping_address, subtotal, tax_amount, shipping_cost, discount_amount, total_amount, payment_method, shipping_method, shipped_at, delivered_at, created_at) VALUES 
('ORD-001', 1, 'delivered', 'paid', '123 Main Street, New York, NY 10001', 1299.99, 103.99, 15.99, 0, 1419.97, 'credit_card', 'express', '2024-01-15 10:00:00', '2024-01-17 14:30:00', '2024-01-14 16:45:00'),
('ORD-002', 2, 'delivered', 'paid', '456 Oak Avenue, Los Angeles, CA 90001', 999.99, 79.99, 19.99, 50.00, 1049.97, 'paypal', 'standard', '2024-01-20 09:15:00', '2024-01-25 11:20:00', '2024-01-19 14:20:00'),
('ORD-003', 3, 'delivered', 'paid', '789 Pine Road, Chicago, IL 60601', 149.99, 11.99, 12.99, 0, 174.97, 'credit_card', 'standard', '2024-02-01 11:30:00', '2024-02-05 16:45:00', '2024-01-31 10:15:00'),
('ORD-004', 4, 'shipped', 'paid', '321 Elm Street, Houston, TX 77001', 449.99, 35.99, 8.99, 0, 494.97, 'credit_card', 'express', '2024-02-10 13:20:00', NULL, '2024-02-08 09:30:00'),
('ORD-005', 5, 'processing', 'paid', '567 Maple Drive, Phoenix, AZ 85001', 199.99, 15.99, 5.99, 0, 221.97, 'bank_transfer', 'standard', NULL, NULL, '2024-02-12 15:45:00'),
('ORD-006', 6, 'delivered', 'paid', '890 Cedar Lane, Philadelphia, PA 19101', 49.99, 3.99, 0, 0, 53.98, 'credit_card', 'standard', '2024-02-15 08:45:00', '2024-02-18 12:30:00', '2024-02-14 11:20:00'),
('ORD-007', 7, 'delivered', 'paid', '234 Birch Street, San Antonio, TX 78201', 2499.99, 199.99, 29.99, 0, 2729.97, 'credit_card', 'overnight', '2024-02-20 07:00:00', '2024-02-21 10:15:00', '2024-02-19 16:30:00'),
('ORD-008', 8, 'cancelled', 'refunded', '678 Spruce Avenue, San Diego, CA 92101', 149.99, 11.99, 12.99, 0, 174.97, 'paypal', 'standard', NULL, NULL, '2024-02-22 13:45:00'),
('ORD-009', 9, 'delivered', 'paid', '345 Fir Road, Dallas, TX 75201', 799.99, 63.99, 19.99, 0, 883.97, 'credit_card', 'express', '2024-02-25 12:30:00', '2024-02-27 15:20:00', '2024-02-24 10:15:00'),
('ORD-010', 10, 'delivered', 'paid', '789 Pine Street, San Jose, CA 95101', 349.99, 27.99, 8.99, 0, 386.97, 'credit_card', 'express', '2024-03-01 09:45:00', '2024-03-03 14:30:00', '2024-02-28 16:20:00');

-- Order Items (Junction table connecting orders to products)
INSERT INTO order_items (order_id, product_id, quantity, unit_price, discount_amount, tax_amount, total_price) VALUES 
(1, 1, 1, 1299.99, 0, 103.99, 1299.99),
(2, 2, 1, 999.99, 50.00, 79.99, 949.99),
(3, 3, 1, 149.99, 0, 11.99, 149.99),
(4, 9, 1, 449.99, 0, 35.99, 449.99),
(5, 12, 1, 199.99, 0, 15.99, 199.99),
(6, 4, 1, 49.99, 0, 3.99, 49.99),
(7, 7, 1, 2499.99, 0, 199.99, 2499.99),
(8, 8, 1, 149.99, 0, 11.99, 149.99),
(9, 2, 1, 999.99, 0, 79.99, 799.99),
(10, 6, 1, 349.99, 0, 27.99, 349.99);

-- Reviews (Rich review data for semantic search demonstrations)
INSERT INTO reviews (product_id, user_id, order_id, rating, title, comment, pros, cons, is_verified_purchase, helpful_count) VALUES 
(1, 1, 1, 5, 'Best laptop I have ever owned!', 'I have been using the UltraBook Pro 15 for three months now, and it has exceeded all my expectations. As a software developer and part-time content creator, I needed a machine that could handle heavy development environments, video editing, and occasional gaming. This laptop delivers on all fronts. The 4K OLED display is absolutely stunning - colors are vibrant and accurate, making photo and video editing a joy. The keyboard has excellent travel and tactile feedback, which is crucial for long coding sessions. Battery life is impressive considering the powerful hardware; I easily get 8-9 hours with mixed usage. The build quality is exceptional - the aluminum chassis feels premium and sturdy. Performance-wise, compiling large projects is blazingly fast, and I can run multiple Docker containers without any slowdown. The RTX 3070 handles my video rendering tasks efficiently and even runs modern games at high settings. The only minor complaint is that it can get warm during intensive tasks, but the fan noise is reasonable. Overall, this is a fantastic machine that is worth every penny.', 'Amazing 4K display, excellent performance, great build quality, comfortable keyboard, good battery life', 'Can get warm under heavy load, premium price point', true, 15),
(1, 6, NULL, 4, 'Great performance but battery could be better', 'The UltraBook Pro 15 is a powerhouse for sure. I use it primarily for data analysis and machine learning tasks. The processing power is incredible - training models that took hours on my old laptop now complete in minutes. The display quality is outstanding, making it easy to work with multiple windows and detailed visualizations. However, the battery life is not as good as advertised. When running intensive computations, I barely get 4-5 hours. For lighter tasks like web browsing and document editing, it does last longer, around 7-8 hours. The laptop also runs quite hot during heavy workloads, though the cooling system does its job. Despite these issues, the performance gains make it worthwhile for professional use.', 'Exceptional processing power, brilliant display, fast SSD, quality construction', 'Battery drains quickly under load, runs hot, expensive', false, 8),
(1, 11, NULL, 5, 'Perfect for creative professionals', 'As a graphic designer and video editor, this laptop has transformed my workflow. The color accuracy of the OLED display is phenomenal - what I see on screen matches perfectly with printed outputs. Rendering times have decreased dramatically compared to my previous setup. The keyboard is comfortable for long typing sessions, and the trackpad is responsive and accurate. Battery life is decent for a high-performance machine - I get about 6-7 hours of design work. The variety of ports means I do not need dongles for my external drives and monitors. Build quality is top-notch; it feels like it could survive anything.', 'Stunning display accuracy, powerful graphics card, excellent build quality, good port selection', 'Heavy for daily carrying, fans can be loud under load', false, 12),
(2, 2, 2, 4, 'Great phone with minor quirks', 'After switching from my 3-year-old phone to the SmartPhone X Pro, the difference is night and day. The 120Hz display makes everything buttery smooth - scrolling through social media, playing games, and even just navigating the UI feels incredibly responsive. The camera system is phenomenal; I have taken some of my best photos ever with this phone. The night mode is particularly impressive, capturing clear shots in conditions where my old phone would produce grainy, unusable images. The 5G speeds are fantastic where available, making streaming and downloads incredibly fast. Face unlock works flawlessly, even in low light. However, I do have a few complaints. The phone is quite large and can be unwieldy for one-handed use. Despite the large battery, heavy usage especially with 5G and the 120Hz display enabled can drain it faster than expected. The in-display fingerprint sensor, while convenient, is not as fast or reliable as the physical sensors I am used to. Also, the phone can get noticeably warm during extended gaming sessions or when using the camera for long periods.', 'Stunning 120Hz display, excellent camera system, fast 5G connectivity, smooth performance', 'Large size, fingerprint sensor could be better, gets warm during intensive use', true, 22),
(2, 7, NULL, 5, 'Camera quality is incredible', 'The SmartPhone X Pro has the best camera I have ever used on a phone. The 108MP main sensor captures an insane amount of detail. I have printed some photos at large sizes and they look professional. The night mode is magical - I can take clear photos in almost complete darkness. Video quality is equally impressive with smooth stabilization. Battery life easily lasts me a full day, even with heavy camera use. The fast charging is a lifesaver - 15 minutes gives me enough juice for hours. The display is gorgeous and the 120Hz refresh rate makes everything feel premium.', 'Outstanding camera quality, excellent battery life, fast charging, smooth display', 'Expensive, can be slippery without a case', false, 18),
(2, 12, NULL, 3, 'Good phone but battery disappoints', 'I had high expectations for the SmartPhone X Pro, and while it excels in many areas, the battery life has been disappointing. Despite the 5000mAh capacity, I find myself charging twice a day with moderate use. The camera is indeed excellent, producing sharp and vibrant photos. The performance is smooth, and apps load quickly. However, for a flagship phone at this price point, I expected better battery optimization. The phone also tends to heat up during video calls or when using GPS navigation for extended periods.', 'Great camera, smooth performance, beautiful display', 'Poor battery life, overheating issues, high price', false, 5),
(3, 3, 3, 5, 'Kitchen game-changer!', 'The PowerBlend 3000 has revolutionized my morning routine and overall approach to healthy eating. I bought this primarily for making smoothies, but it is capable of so much more. The motor is incredibly powerful - it pulverizes frozen fruits, ice, and even tough vegetables like kale and carrots into perfectly smooth consistency. I have made almond butter, cashew cream, and even hot soup using the friction heat from the blades. The preset programs are genuinely useful, not just gimmicks. The smoothie setting creates the perfect consistency every time, and the soup program heats ingredients to serving temperature while blending. The self-cleaning mode actually works - just add warm water and a drop of dish soap, run the cycle, and it is clean. The large container is perfect for batch preparation. I make enough smoothie for the entire week and store portions in mason jars. The noise level is very acceptable for such a powerful motor - much quieter than my previous blender. The tamper is essential for thick mixtures. Build quality feels commercial-grade. After 6 months of daily use, it still looks and performs like new. Absolutely worth the investment for anyone serious about healthy eating.', 'Incredibly powerful motor, versatile functionality, useful preset programs, easy to clean, durable construction', 'Takes up counter space, initial learning curve for optimal results', true, 28),
(3, 8, NULL, 5, 'Powerful and easy to use', 'This blender is a beast! It crushes ice like nothing, makes the smoothest smoothies, and even handles hot soups. The preset programs take the guesswork out of blending. I especially love the self-cleaning function - it actually works! My green smoothies come out silky smooth with no chunks of kale or spinach. The build quality is excellent; it feels like a commercial unit. Worth every penny for daily smoothie makers.', 'Extremely powerful, great presets, easy cleaning, solid build', 'Large footprint, slightly noisy', false, 14),
(3, 13, NULL, 4, 'Great blender but very loud', 'The PowerBlend 3000 delivers on performance. It blends everything to a perfectly smooth consistency, from frozen fruits to nuts. The preset programs are convenient and work well. However, this thing is LOUD. Much louder than advertised. I cannot use it early in the morning without waking everyone up. Also, while the self-cleaning works, you still need to disassemble and deep clean occasionally. Despite the noise, it is a quality blender that does its job well.', 'Powerful blending, useful programs, sturdy construction', 'Very loud operation, requires occasional deep cleaning', false, 9),
(4, 4, NULL, 5, 'Essential resource for programmers', 'As someone who has been programming for 5 years and recently transitioned into a senior developer role, I found "The Art of Coding" to be an invaluable resource. What sets this book apart is its comprehensive coverage and practical approach. It does not just teach syntax - it teaches you how to think like a programmer. The progression from basic concepts to advanced topics is well-structured and logical. Each chapter builds upon previous knowledge while introducing new concepts at a digestible pace. The real-world examples are particularly helpful - instead of contrived examples, the authors use scenarios you are likely to encounter in actual projects. The section on design patterns finally made concepts like dependency injection and factory patterns click for me. The algorithm explanations with visual diagrams are excellent. The multi-language approach is brilliant - seeing the same concepts implemented in Python, JavaScript, Java, and Go really reinforces understanding. The QR codes linking to video content are a nice touch, especially for complex topics. The book is hefty but well-organized with a comprehensive index. I particularly appreciate the "common pitfalls" sections that highlight mistakes beginners often make. This book has earned a permanent spot on my desk as a reference guide.', 'Comprehensive coverage, excellent real-world examples, multi-language approach, great visual explanations, helpful online resources', 'Large size makes it less portable, some sections may be too basic for experienced developers', false, 25),
(4, 9, NULL, 5, 'Best programming book I have read', 'This book is a masterpiece. It covers everything from basic programming concepts to advanced architectural patterns. The writing is clear and engaging, making complex topics accessible. The code examples are practical and well-commented. I particularly appreciated the sections on testing and debugging - skills often overlooked in other books. The online resources accessed via QR codes add tremendous value. This book has made me a better programmer.', 'Comprehensive content, clear explanations, practical examples, excellent online resources', 'Heavy to carry around, somewhat expensive', false, 19),
(4, 14, NULL, 4, 'Great content but outdated in some areas', 'The Art of Coding is an excellent resource with comprehensive coverage of programming concepts. The explanations are clear and the examples are helpful. However, some sections feel outdated, particularly the web development chapters which do not cover the latest frameworks. The book is also quite heavy, making it impractical for commute reading. Despite these issues, it is still a valuable resource for understanding core programming principles that transcend specific technologies.', 'Solid fundamentals, good examples, clear writing', 'Some outdated content, very heavy, pricey', false, 7);